---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-disk
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.22
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: "/var/lib/mysql"
              subPath: "mysql"
            - name: init-sql-data
              mountPath: "/docker-entrypoint-initdb.d/00-schema.sql"
              subPath: 'schema.sql'
              readOnly: true
            - name: init-sql-data
              mountPath: "/docker-entrypoint-initdb.d/10-users.sql"
              subPath: 'users.sql'
              readOnly: true
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "metagamer"
          args: ['--sql-mode=', '--default-authentication-plugin=mysql_native_password']
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk
        - name: init-sql-data
          configMap:
            name: sql-init

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3308
    targetPort: 3306

...
